name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - homologacao:
              bucket: "aws s3api create-bucket --bucket meu-bucket-de-homologacao --region us-east-1"
          - producao:
              bucket: "seu-bucket-de-producao"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Environment
      run: |
        if [[ "${{ matrix.environment }}" == "homologacao" ]]; then
          echo "Implantação em homologação"
          # Use ferramentas de linha de comando AWS ou outros comandos necessários
          # para enviar os arquivos para o bucket de homologação.
        elif [[ "${{ matrix.environment }}" == "producao" ]]; then
          echo "Implantação em produção"
          # Verifique se existe um determinado conteúdo no commit
          if git log -n 1 --pretty=format:%B | grep -q "SeuTextoAqui"; then
            # Use ferramentas de linha de comando AWS ou outros comandos necessários
            # para enviar os arquivos para o bucket de produção.
          else
            echo "Nenhum conteúdo correspondente no commit. Ignorando implantação em produção."
          fi
        else
          echo "Ambiente não reconhecido."
          exit 1
        fi

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
